python3 -m da.compiler olympus.da
python3 -m da.compiler replica.da
python3 -m da.compiler classes.da
python3 -m da.compiler constants.da
python3 -m da.compiler logger.da
python3 -m da.compiler client.da
python3 -m da.compiler main.da
python3 -m da.compiler util.da
python3 -m da.compiler timer.da
